# Generated by Django 5.2.5 on 2025-08-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urunozellik',
            old_name='kodu',
            new_name='kod',
        ),
    ]
