# Generated by Django 5.2.5 on 2025-08-25 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raf_ad', models.CharField(max_length=1)),
                ('raf_tekil_barkod', models.CharField(max_length=10)),
                ('raf_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_ad', models.CharField(max_length=100)),
                ('urun_barkod', models.IntegerField(default=0)),
                ('urun_id', models.IntegerField(default=0)),
                ('urun_adet', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Satis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('raf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.raf')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.urun')),
            ],
        ),
        migrations.CreateModel(
            name='Alis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('raf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.raf')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.urun')),
            ],
        ),
        migrations.CreateModel(
            name='RafUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=0)),
                ('raf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raf_urunleri', to='erp_app.raf')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urun_raflari', to='erp_app.urun')),
            ],
            options={
                'unique_together': {('raf', 'urun')},
            },
        ),
    ]
