# Generated by Django 5.2.5 on 2025-08-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raf',
            name='raf_ad',
            field=models.CharField(max_length=10),
        ),
    ]
